### ISSUE TITLE
Ошибка при генерации ключей Unexpected end of JSON input

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#133]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async file:///app/app/services/BaseKeyGenerateService.js:60:26
    at async GangsWarsKeyGenerateService.login (file:///app/app/services/BaseKeyGenerateService.js:51:26)
    at async GangsWarsKeyGenerateService.generateKey (file:///app/app/services/BaseKeyGenerateService.js:116:9)
    at async Promise.all (index 2)
```

**Comment by m0nclous** [comment]
В релизе v1.5.1
