### ISSUE TITLE
Ошибка при генерации ключей Request failed with status code 503 Service Unavailable

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#134]
```
HTTPError: Request failed with status code 503 Service Unavailable: Back-end server is at capacity: POST https://api.gamepromo.io/promo/register-event
    at function_ (file:///app/node_modules/ky/distribution/core/Ky.js:28:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GangsWarsKeyGenerateService.processKey (file:///app/app/services/BaseKeyGenerateService.js:78:26)
    at async GangsWarsKeyGenerateService.generateKey (file:///app/app/services/BaseKeyGenerateService.js:119:29)
    at async Promise.all (index 0)
```

**Comment by m0nclous** [comment]
В релизе v1.5.1
