### ISSUE TITLE
Ошибки 401: AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#135]
```
RPCError: 401: AUTH_KEY_UNREGISTERED (caused by contacts.ResolveUsername)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:546:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:476:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:424:17)
```

**Comment by m0nclous** [comment]
Исправлено в релизе v1.5.1
